#!/bin/sh
set -eu

sudo apt-get -q update
cabal install alex
cabal install happy
cabal install gtk2hs-buildtools
sudo apt-get -q -y install pkg-config
cabal install glib
sudo apt-get -q -y install libtag1c2a
sudo apt-get -q -y install libtag1-dev
