#!/bin/sh
set -eu

sudo apt-get -q update
sudo apt-get -q -y install alex
sudo apt-get -q -y install happy
#cabal install alex
#cabal install happy
cabal install gtk2hs-buildtools
sudo apt-get -q -y install pkg-config
cabal install glib
sudo apt-get -q -y install libtag1c2a
sudo apt-get -q -y install libtag1-dev
sudo apt-get -q -y install libtagc0
sudo apt-get -q -y install libtagc0-dev
cabal install libtagc
